export const areas = [
  "Alexandra Hill",
  "Alexandra North",
  "Aljunied",
  "Anak Bukit",
  "Anson",
  "Balestier",
  "Bayfront Subzone",
  "Bencoolen",
  "Bendemeer",
  "Bidadari",
  "Bishan East",
  "Boat Quay",
  "Boon Keng",
  "Boon Teck",
  "Boulevard",
  "Braddell",
  "Bras Basah",
  "Bugis",
  "Bukit Ho Swee",
  "Bukit Merah",
  "Cairnhill",
  "Cecil",
  "Central Subzone",
  "Chatsworth",
  "China Square",
  "Chinatown",
  "City Hall",
  "City Terminals",
  "Clarke Quay",
  "Clifford Pier",
  "Commonwealth",
  "Coronation Road",
  "Crawford",
  "Depot Road",
  "Dhoby Ghaut",
  "Dover",
  "Dunearn",
  "East Coast",
  "Everton Park",
  "Farrer Court",
  "Farrer Park",
  "Fort Canning",
  "Geylang Bahru",
  "Geylang East",
  "Ghim Moh",
  "Goodwood Park",
  "Henderson Hill",
  "Hillcrest",
  "Holland Drive",
  "Holland Road",
  "Institution Hill",
  "Istana Negara",
  "Joo Seng",
  "Kallang Bahru",
  "Kallang Way",
  "Kampong Bugis",
  "Kampong Glam",
  "Kampong Java",
  "Kampong Tiong Bahru",
  "Kampong Ubi",
  "Katong",
  "Kent Ridge",
  "Kim Keat",
  "Lavender",
  "Leedon Park",
  "Leonie Hill",
  "Little India",
  "Lorong 8 Toa Payoh",
  "Mackenzie",
  "MacPherson",
  "Malcolm",
  "Margaret Drive",
  "Marina Centre",
  "Marina East",
  "Marina East",
  "Marina South",
  "Marine Parade",
  "Maritime Square",
  "Marymount",
  "Maxwell",
  "Mei Chin",
  "Monk's Hill",
  "Moulmein",
  "Mount Emily",
  "Mount Pleasant",
  "Mountbatten",
  "Nassim",
  "National University of Singapore",
  "Newton Circus",
  "Nicoll",
  "One Tree Hill",
  "one-north",
  "Orange Grove",
  "Oxley",
  "Pasir Panjang 1",
  "Pasir Panjang 2",
  "Paterson",
  "Pearl's Hill",
  "Pei Chun",
  "People's Park",
  "Phillip",
  "Port",
  "Potong Pasir",
  "Queensway",
  "Raffles Place",
  "Redhill",
  "Ridout",
  "Robertson Quay",
  "Rochor Canal",
  "Selegie",
  "Sennett",
  "Sentosa",
  "Singapore General Hospital",
  "Singapore Polytechnic",
  "Somerset",
  "Southern Group",
  "Straits View",
  "Sungei Road",
  "Swiss Club",
  "Tanglin",
  "Tanglin Halt",
  "Tanjong Pagar",
  "Tanjong Rhu",
  "Telok Blangah Drive",
  "Telok Blangah Rise",
  "Telok Blangah Way",
  "Tiong Bahru",
  "Tiong Bahru Station",
  "Toa Payoh Central",
  "Toa Payoh West",
  "Tyersall",
  "Ulu Pandan",
  "Upper Thomson",
  "Victoria",
  "Woodleigh",
];
